version: '3.9'
services:
  backend:
    image: ${BACKEND_IMAGE:-ghl/backend:latest}
    restart: unless-stopped
    env_file:
      - ./env/backend.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - ghl-net

  client:
    image: ${CLIENT_IMAGE:-ghl/client:latest}
    restart: unless-stopped
    env_file:
      - ./env/client.env
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - ghl-net

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ghl-net

volumes:
  db_data:

networks:
  ghl-net:
    driver: bridge 